### ISSUE TITLE
Tagged release shows the wrong date

### ISSUE THREAD

**Issue by robberize** [eduperez/mwlwifi#1]
@eduperez 

Firstly thank you for sharing these pre-compiled **mwlwifi** driver packages with everyone.

Github does not accurately display your package release date. Currently `10.3.4.0-20170512` commit `f8a3c79` released `May 11, 2017` by **kaloz** shows the following.

> eduperez released this 8 days ago.

This is obviously not possible. Have you noticed this before?

**Comment by eduperez** [comment]
Yes, I did notice that: my repository does not contain any "sources" other than the "README" file on the homepage; thus, from the point of view of github, all my releases are based on the same commit (last time I changed the README file), and the "release time" of each binary is always the time of the last commit.

It's harmless but annoying... I should probably do a proper cloning of kaloz's repo (even if I am not changing any code) sometime soon, so my releases are dated with his commits.

**Comment by robberize** [comment]
I wasn't sure what the issue was. Thanks for the quick feedback.

**Comment by eduperez** [comment]
I have created the "mwlwifi_LEDE" repository, as a clone of kaloz's repository, and made a proper release for the latest code available; now labels and dates match. I will rename this repository and close it in a few days.
